version: "3.8"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: base_api
        container_name: app_api
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - db
        volumes:
            - ./:/var/www
        networks:
            - base_api

    db:
        container_name: db_api
        image: postgres:15
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_DATABASE}
        restart: unless-stopped
        volumes:
            - /postgres:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
        networks:
            - base_api
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -d $DB_DATABASE -U $DB_USERNAME"
                ]
            interval: 5s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:alpine
        container_name: nginx_api
        restart: unless-stopped
        ports:
            - "7000:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/
        networks:
            - base_api
        depends_on:
            - app

networks:
    base_api:
        driver: bridge
